"""Add currency and contacted to Pledge

Revision ID: 253a3c3f74ae
Revises: 491566303e70
Create Date: 2026-05-12 23:32:57.888850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253a3c3f74ae'
down_revision: Union[str, None] = '491566303e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pledge', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('pledge', sa.Column('contacted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pledge', 'contacted')
    op.drop_column('pledge', 'currency')
    # ### end Alembic commands ###
