"""Add is_superuser to User

Revision ID: 36f8a5b70304
Revises: 253a3c3f74ae
Create Date: 2026-05-19 00:26:41.404531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f8a5b70304'
down_revision: Union[str, None] = '253a3c3f74ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
